# Generated by Django 3.0.3 on 2020-04-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=125)),
                ('first_name', models.CharField(max_length=125)),
                ('last_name', models.CharField(max_length=125)),
                ('raiting', models.IntegerField(default=1600)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, unique=True)),
                ('title', models.CharField(max_length=125)),
                ('text', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('is_visible', models.BooleanField(default=False)),
                ('tournament_type', models.CharField(default='solo', max_length=10)),
            ],
        ),
    ]
