# Generated by Django 3.0.3 on 2020-04-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wh_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_baned',
            field=models.BooleanField(default=False),
        ),
    ]
