# Generated by Django 3.0.3 on 2020-04-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wh_main', '0002_player_is_baned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='is_baned',
            new_name='baned',
        ),
    ]
