# Generated by Django 3.0.3 on 2020-04-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wh_main', '0003_auto_20200428_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, unique=True)),
                ('text', models.CharField(max_length=500)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('baned', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(to='wh_main.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nick',
            field=models.CharField(max_length=125, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=125),
        ),
    ]
