# Generated by Django 3.0.3 on 2020-04-28 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wh_main', '0004_auto_20200428_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='players',
        ),
        migrations.AddField(
            model_name='tournament',
            name='orginizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wh_main.Organizer'),
            preserve_default=False,
        ),
    ]
