# Generated by Django 3.0.3 on 2020-04-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wh_main', '0005_auto_20200428_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(to='wh_main.Player'),
        ),
    ]
