# Generated by Django 3.0.3 on 2020-04-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wh_main', '0006_tournament_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='link',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
