# Generated by Django 3.0.3 on 2020-04-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wh_main', '0007_tournament_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='points',
            field=models.IntegerField(default=1000),
        ),
    ]
