# Generated by Django 3.0.3 on 2020-04-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wh_main', '0008_tournament_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tours',
            field=models.IntegerField(default=3),
        ),
    ]
