# Generated by Django 3.0.3 on 2020-04-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wh_main', '0009_tournament_tours'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='link',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
