# Generated by Django 3.0.3 on 2020-04-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wh_main', '0011_player_proxibot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
